version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - prefect-kafka-network

    
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-1
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "19092"] 
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 20s
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - prefect-kafka-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8081:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:19092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - prefect-kafka-network
      
  prefect-server:
    image: prefecthq/prefect:3-latest
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    environment:
      PREFECT_LOGGING_LEVEL: INFO
      PREFECT_SERVER_API_AUTH_STRING: "admin:pass"
    volumes:
      - prefect_data:/root/.prefect
    networks:
      - prefect-kafka-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: prefect-db
    restart: unless-stopped
    # TODO: remove ports:
    # TODO: check this https://docs.prefect.io/v3/how-to-guides/self-hosted/docker-compose
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prefect-kafka-network

  prefect-worker:
    build:
      context: ./prefect-worker-demo
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - prefect-server
      - postgres
      - kafka
    env_file:
      - path: prefect-worker-demo/.env
        required: true
    environment:
      PREFECT_API_URL: "http://prefect-server:4200/api"
      PREFECT_API_AUTH_STRING: "admin:pass"
    networks:
      - prefect-kafka-network



  gradio-panel:
    build:
      context: ./message-admin-demo
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_healthy
    env_file:
      - path: message-admin-demo/.env
        required: true
    environment:
      APP_CONFIG__BROKER__KAFKA_BOOTSTRAP_SERVERS: "kafka:19092"
    #   PREFECT_API_AUTH_STRING: "admin:pass"
    networks:
      - prefect-kafka-network

volumes:
  postgres_data:
  prefect_data:
  kafka_data:

networks:
  prefect-kafka-network:
    driver: bridge
